### ISSUE TITLE
CLI：generate no  testcase for folder

### ISSUE THREAD

**Issue by tang4530** [UnitTestBot/UTBotCpp#286] opened 2022-06-17 03:41 UTC
I generated tests for folder. No case is generated.
But I generated tests for one file in the same folder.  Test cases are generated.

**Comment by ladisgin** [comment] 2022-06-30 08:54
Duplicate of #140

**Comment by ladisgin** [comment] 2022-06-30 08:55
Duplicate of #140

**Closed by ladisgin** 2022-06-30 08:55 UTC
Labels: bug
